server:
  port: 8080

spring:
  application:
    name: equity-seer-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tnpdb}
    username: ${DB_USERNAME:riphco}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  name: equity-seer

